// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using i3p_server.Models;

#nullable disable

namespace i3p_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325085339_VibecodedMigration")]
    partial class VibecodedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("i3p_server.Models.AnnualProcurementPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuxilliaryJson")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<double?>("TotalBudget")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AnnualProcurementPlans");
                });

            modelBuilder.Entity("i3p_server.Models.AppItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .HasColumnType("text");

                    b.Property<int>("AnnualProcurementPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("No")
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Specification")
                        .HasColumnType("text");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text");

                    b.Property<string>("Unspsc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnnualProcurementPlanId");

                    b.ToTable("AppItems");
                });

            modelBuilder.Entity("i3p_server.Models.ExpenditureData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuxilliaryJson")
                        .HasColumnType("text");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpenditureData");
                });

            modelBuilder.Entity("i3p_server.Models.ExpenditureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activities")
                        .HasColumnType("text");

                    b.Property<int>("ExpenditureDataId")
                        .HasColumnType("integer");

                    b.Property<string>("ExpenseClass")
                        .HasColumnType("text");

                    b.Property<string>("ExpenseItem")
                        .HasColumnType("text");

                    b.Property<string>("ExpenseObject")
                        .HasColumnType("text");

                    b.Property<double?>("FinancialObligation")
                        .HasColumnType("double precision");

                    b.Property<string>("IsAppSupplies")
                        .HasColumnType("text");

                    b.Property<string>("IsPpmp")
                        .HasColumnType("text");

                    b.Property<string>("MannerOfRelease")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("PerformanceIndicator")
                        .HasColumnType("text");

                    b.Property<string>("PhysicalTarget2026")
                        .HasColumnType("text");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecificProgram")
                        .HasColumnType("text");

                    b.Property<double?>("TotalCost")
                        .HasColumnType("double precision");

                    b.Property<double?>("UnitCost")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ExpenditureDataId");

                    b.ToTable("ExpenditureItem");
                });

            modelBuilder.Entity("i3p_server.Models.ImplementationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .HasColumnType("text");

                    b.Property<string>("AccountTitle")
                        .HasColumnType("text");

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<string>("ArCode")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<double?>("EstimatedCost")
                        .HasColumnType("double precision");

                    b.Property<string>("ExpenditureType")
                        .HasColumnType("text");

                    b.Property<string>("Indicator")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Kra")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.Property<int>("SchoolImplementationId")
                        .HasColumnType("integer");

                    b.Property<string>("SipProgram")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolImplementationId");

                    b.ToTable("ImplementationItems");
                });

            modelBuilder.Entity("i3p_server.Models.PPMP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuxilliaryJson")
                        .HasColumnType("text");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PPMPs");
                });

            modelBuilder.Entity("i3p_server.Models.PlanCrossReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<string>("AppItemDescription")
                        .HasColumnType("text");

                    b.Property<int?>("AppItemId")
                        .HasColumnType("integer");

                    b.Property<double>("AppItemPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ArCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ImplementationItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOrphaned")
                        .HasColumnType("boolean");

                    b.Property<double>("MatchScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SipItemActivity")
                        .HasColumnType("text");

                    b.Property<double?>("SipItemCost")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitCost")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppItemId")
                        .HasDatabaseName("IX_PlanCrossReference_AppItemId");

                    b.HasIndex("ArCode")
                        .HasDatabaseName("IX_PlanCrossReference_ArCode");

                    b.HasIndex("ImplementationItemId");

                    b.HasIndex("Year", "Status")
                        .HasDatabaseName("IX_PlanCrossReference_Year_Status");

                    b.ToTable("PlanCrossReferences");
                });

            modelBuilder.Entity("i3p_server.Models.PpmpItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<double?>("EstimatedBudget")
                        .HasColumnType("double precision");

                    b.Property<string>("GeneralDescription")
                        .HasColumnType("text");

                    b.Property<string>("ModeOfProcurement")
                        .HasColumnType("text");

                    b.Property<int>("PPMPId")
                        .HasColumnType("integer");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("ScheduleJson")
                        .HasColumnType("text");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Units")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PPMPId");

                    b.ToTable("PpmpItem");
                });

            modelBuilder.Entity("i3p_server.Models.ProcurementItemB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ProcurementPlanBId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementPlanBId");

                    b.ToTable("ProcurementItemB");
                });

            modelBuilder.Entity("i3p_server.Models.ProcurementPlanB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuxilliaryJson")
                        .HasColumnType("text");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcurementPlanBs");
                });

            modelBuilder.Entity("i3p_server.Models.SchoolImplementation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AnnualBudget")
                        .HasColumnType("double precision");

                    b.Property<string>("AuxilliaryJson")
                        .HasColumnType("text");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalEstimatedCost")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SchoolImplementations");
                });

            modelBuilder.Entity("i3p_server.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Authority")
                        .HasColumnType("integer")
                        .HasColumnName("authority");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("i3p_server.Models.AppItem", b =>
                {
                    b.HasOne("i3p_server.Models.AnnualProcurementPlan", "AnnualProcurementPlan")
                        .WithMany("Items")
                        .HasForeignKey("AnnualProcurementPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnualProcurementPlan");
                });

            modelBuilder.Entity("i3p_server.Models.ExpenditureItem", b =>
                {
                    b.HasOne("i3p_server.Models.ExpenditureData", null)
                        .WithMany("Items")
                        .HasForeignKey("ExpenditureDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("i3p_server.Models.ImplementationItem", b =>
                {
                    b.HasOne("i3p_server.Models.SchoolImplementation", "SchoolImplementation")
                        .WithMany("Items")
                        .HasForeignKey("SchoolImplementationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolImplementation");
                });

            modelBuilder.Entity("i3p_server.Models.PlanCrossReference", b =>
                {
                    b.HasOne("i3p_server.Models.ImplementationItem", "ImplementationItem")
                        .WithMany("CrossReferences")
                        .HasForeignKey("ImplementationItemId");

                    b.Navigation("ImplementationItem");
                });

            modelBuilder.Entity("i3p_server.Models.PpmpItem", b =>
                {
                    b.HasOne("i3p_server.Models.PPMP", null)
                        .WithMany("Items")
                        .HasForeignKey("PPMPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("i3p_server.Models.ProcurementItemB", b =>
                {
                    b.HasOne("i3p_server.Models.ProcurementPlanB", null)
                        .WithMany("Items")
                        .HasForeignKey("ProcurementPlanBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("i3p_server.Models.AnnualProcurementPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("i3p_server.Models.ExpenditureData", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("i3p_server.Models.ImplementationItem", b =>
                {
                    b.Navigation("CrossReferences");
                });

            modelBuilder.Entity("i3p_server.Models.PPMP", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("i3p_server.Models.ProcurementPlanB", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("i3p_server.Models.SchoolImplementation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
