// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using i3p_server.Models;

#nullable disable

namespace i3p_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124043240_ExpensesDatabaseEntries")]
    partial class ExpensesDatabaseEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("i3p_server.Models.ExpenseSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DbmGrouping")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dbm_grouping");

                    b.Property<string>("ExpenseClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expense_class");

                    b.Property<string>("MannerOfRelease")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manner_of_release");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.ToTable("expense_summaries");
                });

            modelBuilder.Entity("i3p_server.Models.ProcurementDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<int>("SummaryId")
                        .HasColumnType("integer")
                        .HasColumnName("summary_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<double>("TotalQty")
                        .HasColumnType("double precision")
                        .HasColumnName("total_qty");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit_measure");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("procurement_details");
                });

            modelBuilder.Entity("i3p_server.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Authority")
                        .HasColumnType("integer")
                        .HasColumnName("authority");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("i3p_server.Models.ProcurementDetails", b =>
                {
                    b.HasOne("i3p_server.Models.ExpenseSummary", "Summary")
                        .WithMany("Details")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("i3p_server.Models.ExpenseSummary", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
